[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "deeprank2"
version = "2.1.2"
description = "DeepRank2 is an open-source deep learning framework for data mining of protein-protein interfaces or single-residue missense variants."
readme = "README.md"
requires-python = ">=3.10"
keywords = [
    "graph neural network",
    "convolutional neural network",
    "protein-protein interfaces",
    "missense variants",
    "deep learning",
    "pytorch"]
authors = [
    {name = "Giulia Crocioni", email = "g.crocioni@esciencecenter.nl"},
    {name = "Coos Baakman", email = "coos.baakman@radboudumc.nl"},
    {name = "Dani Bodor", email = "d.bodor@esciencecenter.nl"},
    {name = "Daniel Rademaker"},
    {name = "Gayatri Ramakrishnan"},
    {name = "Sven van der Burg"},
    {name = "Li Xue"},
    {name = "Daniil Lepikhov"},
    ]
license = {text = "Apache-2.0 license"}
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10"
]

[project.optional-dependencies]
# development dependency groups
test = [
    "pytest >= 7.4.0",
    "pylint <= 2.15.3",
    "prospector[with_pyroma] <= 1.7.7",
    "bump2version",
    "coverage",
    "pycodestyle",
    "pytest-cov",
    "pytest-runner",
    "coveralls",
]
publishing = [
    "build",
    "twine",
    "wheel",
]

[project.urls]
Documentation = "https://deeprank2.readthedocs.io/en/latest/?badge=latest"
Repository = "https://github.com/DeepRank/deeprank2"
Changelog = "https://github.com/DeepRank/deeprank2/blob/main/CHANGELOG.md"

[tool.coverage.run]
branch = true
source = ["deeprank2"]

[tool.setuptools.packages.find]
include = ["deeprank2*"]
exclude = ["tests*", "*tests.*", "*tests"]

[tool.setuptools.package-data]
"*" = [
    "*.xlsx",
    "*.param",
    "*.top", 
    "*residue-classes"]
