name: "Install Python and DeepRank2"

description: "Installs Python, updates pip and installs DeepRank2 together with its dependencies."

defaults:
  run:
    shell: bash -el {0}

inputs:

  python-version:
    required: false
    description: "The Python version to use. Specify major and minor version, e.g. '3.10'."
    default: "3.10"

  extras-require:
    required: false
    description: "The extras dependencies packages to be installed, for instance 'dev' or 'dev,publishing,notebooks'."
    default: "test"

runs:

  using: "composite"

  steps:
    - name: Cancel Previous Runs and Set up Python
      uses: styfle/cancel-workflow-action@0.4.0
      with:
          access_token: ${{ github.token }}
    - uses: actions/checkout@v3
    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: ${{ inputs.python-version }}
        activate-environment: deeprank2
        environment-file: env/environment.yml
    - run: conda --version
      shell: bash {0}
    - name: Python info
      shell: bash -e {0}
      run: |
        which python3
        python3 --version
    - name: Install dependencies on Linux
      shell: bash {0}
      env:
        CMAKE_INSTALL_PREFIX: .local
      if: runner.os == 'Linux'
      run: |
        # Install dependencies
        conda env update --file ./env/environment.yml
    - name: Install the package
      shell: bash {0}
      run: pip install .'[${{ inputs.extras-require }}]'
