name: "Install Python and DeepRank2"

description: "Installs Python, updates pip and installs DeepRank2 together with its dependencies."

inputs:
  python-version:
    required: false
    description: "The Python version to use. Specify major and minor version, e.g. '3.10'."
    default: "3.10"

  extras-require:
    required: false
    description: "The extras dependencies packages to be installed, for instance 'dev' or 'dev,publishing,notebooks'."
    default: "test"

  pkg-installation-type:
    required: false
    description: "The package installation type to install, the latest released version on PyPI ('latest') or the GitHub repository one ('repository')."
    default: "repository"

runs:
  using: "composite"

  steps:
    - name: Cancel Previous Runs and Set up Python
      uses: styfle/cancel-workflow-action@0.4.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v3
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ inputs.python-version }}
        conda-channels: pytorch, pyg, bioconda, defaults, sbl, conda-forge
    - run: |
        conda --version
        conda env list
      shell: bash {0}
    - name: Python info
      shell: bash -e {0}
      run: |
        which python3
        python3 --version
    - name: Install dependencies on Linux
      shell: bash {0}
      env:
        CMAKE_INSTALL_PREFIX: .local
      if: runner.os == 'Linux'
      run: |
        # Install deeprank2 conda dependencies
        ## sbl channel
        conda install dssp>=4.2.2.1 -c sbl
        ## bioconda channel
        conda install msms>=2.6.1 markov_clustering>=0.0.6 -c bioconda
        ## pytorch and pyg channels
        ### Installing for CPU only on the CI
        conda install pytorch=2.1.1 torchvision=0.16.1 torchaudio=2.1.1 cpuonly=2.0.* -c pytorch
        conda install pyg=2.4.0 pytorch-scatter=2.1.2 pytorch-sparse=0.6.18 pytorch-cluster=1.6.3 pytorch-spline-conv=1.2.2 -c pyg
        ## conda-forge channel
        conda install tables>=3.8.0 numpy>=1.21.5 scipy>=1.11.2 h5py>=3.6.0 networkx>=2.6.3 matplotlib>=3.5.1 scikit-learn>=1.0.2 chart-studio>=1.1.0 biopython>=1.81 python-louvain>=0.16 tqdm>=4.63.0 freesasa>=2.1.0 tensorboard>=0.9.0 protobuf>=3.20.1 ruff>=0.1.13 dill>=0.3.8 -c conda-forge
    - name: Install dependencies on MacOS
      shell: bash {0}
      env:
        CMAKE_INSTALL_PREFIX: .local
      if: runner.os == 'macOS'
      run: |
        # Install dependencies not handled by setuptools
        ## DSSP
        conda install -c sbl dssp>=4.2.2.1
        ## MSMS
        cd /tmp/
        wget http://mgltools.scripps.edu/downloads/tars/releases/MSMSRELEASE/REL2.6.1/msms_i86Linux2_2.6.1.tar.gz
        sudo mkdir /usr/local/lib/msms
        cd /usr/local/lib/msms
        sudo tar zxvf /tmp/msms_i86Linux2_2.6.1.tar.gz
        sudo ln -s /usr/local/lib/msms/msms.i86Linux2.2.6.1 /usr/local/bin/msms
        sudo ln -s /usr/local/lib/msms/pdb_to_xyzr* /usr/local/bin
        ## PyTorch, PyG, PyG adds
        ### Installing for CPU only on the CI
        conda install pytorch torchvision torchaudio cpuonly -c pytorch
        pip install torch_geometric
        pip install torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-$(python3 -c "import torch; print(torch.__version__)")+cpu.html
        # PyTables via conda only for MacOS
        conda install pytables
    - name: Install the GitHub repository version of the package
      shell: bash {0}
      if: ${{ inputs.pkg-installation-type == 'repository' }}
      run: pip install .'[${{ inputs.extras-require }}]'
    - name: Install the latest released version of the package
      shell: bash {0}
      if: ${{ inputs.pkg-installation-type == 'latest' }}
      run: |
        pip install pytest
        rm -r deeprank2
        pip install deeprank2
