name: build

on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]


jobs:

  build:
    name: Build for (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-python-and-package
      - name: Test with pytest
        env:
          CONDA_PREFIX: /usr/share/miniconda
        run: |
          pytest -v --ignore tests/integration
      - name: Verify that we can build the package
        run: python3 setup.py sdist bdist_wheel

  integration:
    name: Test with GPU
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: [3.9]

    steps:
      - uses: "namiyousef/action-kaggle-gpu-test@main"
        with:
          git_access_token: ${{ secrets.GITHUB_TOKEN }}
          kaggle_api_key: ${{ secrets.KAGGLE_API_KEY }}
          repository_name: ${{ github.repository }}
          test_folder: tests/integration