name: build

on:
  push:
    # paths-ignore:
    #   - "**.md"
    #   - "**.rst"
    #   - "**.ipynb"
    # paths:
    #   - "deeprankcore/**"
    #   - "tests/**"
    #   - ".github/workflows/build.yml"
    #   - ".github/actions/install-python-and-package/action.yml"
    #   - "setup.cfg"
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened, ready_for_review]
    # paths-ignore:
    #   - "**.md"
    #   - "**.rst"
    #   - "**.ipynb"
    # paths:
    #   - "deeprankcore/**"
    #   - "tests/**"
    #   - ".github/workflows/build.yml"
    #   - ".github/actions/install-python-and-package/action.yml"
    #   - "setup.cfg"

jobs:
  build:
    if: github.event.pull_request.draft == false
    name: Build for (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.9', '3.10']

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-python-and-package
      - name: Run unit tests
        env:
          CONDA_PREFIX: /usr/share/miniconda
        run: |
          pytest -v
      - name: Verify that we can build the package
        run: python3 setup.py sdist bdist_wheel