name: build (latest release)

# Only trigger, when the release workflow succeeded
on:
  workflow_run:
    workflows: ["Build and upload to PyPI"]
    types:
      - completed

jobs:
  build:
    name: Build for (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10"] # ["3.10", "3.11"]

    # https://github.com/marketplace/actions/setup-miniconda#use-a-default-shell
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-python-and-package
        with:
          python-version: ${{ matrix.python-version }}
          pkg-installation-type: "latest"
      - name: Run unit tests
        run: pytest -v
