name: coveralls

on:
  push:
    paths-ignore:
      # specific folder locations
      - ".vscode/**"
      - "docs/**"
      # filetypes
      - "**.md"
      - "**.rst"
      - "**.ipynb"
      - "**.cff"
      - "**.png"
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      # specific folder locations
      - ".vscode/**"
      - "docs/**"
      # filetypes
      - "**.md"
      - "**.rst"
      - "**.ipynb"
      - "**.cff"
      - "**.png"

jobs:
  build:
    if: github.event.pull_request.draft == false
    name: Coveralls
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-python-and-package
        with:
          python-version: ${{ matrix.python-version }}
          extras-require: test
      - name: Run unit tests with coverage
        run: pytest --cov --cov-append --cov-report xml --cov-fail-under=80 --cov-report term --cov-report html
      - name: Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          COVERALLS_FLAG_NAME: python-${{ matrix.os }}
        run: |
          coveralls --service=github
