name: coveralls

on:
  push:
    paths:
      # specific folder locations
      - "deeprankcore/**"
      - "tests/**"
      # exclude filetypes
      - "!**.md"
      - "!**.rst"
      - "!**.ipynb"
      # self
      - ".github/workflows/coveralls.yml"
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      # specific folder locations
      - "deeprankcore/**"
      - "tests/**"
      # exclude filetypes
      - "!**.md"
      - "!**.rst"
      - "!**.ipynb"
      # self
      - ".github/workflows/coveralls.yml"

jobs:
  build:
    if: github.event.pull_request.draft == false
    name: Coveralls
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-python-and-package
      - name: Run unit tests with coverage
        run: pytest --cov --cov-append --cov-report xml --cov-report term --cov-report html
      - name: Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          COVERALLS_FLAG_NAME: python-${{ matrix.os }}
        run: |
          coveralls --service=github