name: fair-software

on:
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened, ready_for_review]

jobs:
  verify:
    if: github.event.pull_request.draft == false
    name: "fair-software"
    runs-on: ubuntu-latest
    steps:
      - uses: fair-software/howfairis-github-action@0.2.1
        name: Measure compliance with fair-software.eu recommendations
        env:
          PYCHARM_HOSTED: "Trick colorama into displaying colored output" 
        with:
          MY_REPO_URL: "https://github.com/${{ github.repository }}"
