name: markdown-link-check

on:
  push:
    branches:
    - main
    paths:
      # filetypes
      - "**.md"
      - "**.rst"
      # self
      - ".github/workflows/markdown-link-check.yml"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      # filetypes
      - "**.md"
      - "**.rst"
      # self
      - ".github/workflows/markdown-link-check.yml"

jobs:
  markdown-link-check:
    if: github.event.pull_request.draft == false
    name: Check markdown links
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: '.github/workflows/markdown-link-check.yml'
