# SPDX-FileCopyrightText: 2022 Christian Meeßen (GFZ) <christian.meessen@gfz-potsdam.de>
# SPDX-FileCopyrightText: 2022 Dusan Mijatovic (dv4all)
# SPDX-FileCopyrightText: 2022 Helmholtz Centre Potsdam - GFZ German Research Centre for Geosciences
# SPDX-FileCopyrightText: 2022 dv4all
# SPDX-FileCopyrightText: 2023 - 2024 Dusan Mijatovic (Netherlands eScience Center)
# SPDX-FileCopyrightText: 2023 - 2024 Ewan Cahen (Netherlands eScience Center) <e.cahen@esciencecenter.nl>
# SPDX-FileCopyrightText: 2023 - 2024 Netherlands eScience Center
#
# SPDX-License-Identifier: Apache-2.0

name: Create and publish a Docker image

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches: ["529_add_docker_testing_action_gcroci2"]

jobs:
  read_version:
    name: Read version from TOML
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
      repo_lowercase: ${{ steps.repo_lowercase.outputs.REPO_LOWERCASE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read version from TOML
        id: get_version
        run: |
          VERSION=$(grep '^version =' pyproject.toml | awk -F '"' '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Convert repository name to lowercase
        id: repo_lowercase
        run: |
          REPO_LOWERCASE=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_LOWERCASE=$REPO_LOWERCASE" >> $GITHUB_OUTPUT

  docker_image_deeprank2:
    needs: read_version
    name: docker_image_deeprank2
    uses: ./.github/workflows/_ghcr.yml
    with:
      ghcr_user: ${{github.actor}}
      base_image_name: ghcr.io/${{ needs.read_version.outputs.repo_lowercase }}
      image_tag: ${{ needs.read_version.outputs.version }}
      dockerfile: ./Dockerfile
      docker_context: .
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}
