# SPDX-FileCopyrightText: 2022 Christian Meeßen (GFZ) <christian.meessen@gfz-potsdam.de>
# SPDX-FileCopyrightText: 2022 Dusan Mijatovic (dv4all)
# SPDX-FileCopyrightText: 2022 Helmholtz Centre Potsdam - GFZ German Research Centre for Geosciences
# SPDX-FileCopyrightText: 2022 dv4all
# SPDX-FileCopyrightText: 2023 - 2024 Dusan Mijatovic (Netherlands eScience Center)
# SPDX-FileCopyrightText: 2023 - 2024 Ewan Cahen (Netherlands eScience Center) <e.cahen@esciencecenter.nl>
# SPDX-FileCopyrightText: 2023 - 2024 Netherlands eScience Center
#
# SPDX-License-Identifier: Apache-2.0

name: Create and publish a Docker image

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches: ["529_add_docker_testing_action_gcroci2"]

jobs:
  release_tag:
    name: conventional changelog
    runs-on: ubuntu-22.04
    outputs:
      changelog: ${{steps.changelog.outputs.clean_changelog}}
      tag: ${{steps.changelog.outputs.tag}}
      skipped: ${{steps.changelog.outputs.skipped}}
    steps:
      - name: checkout all history
        # https://github.com/actions/checkout
        uses: actions/checkout@v4
        with:
          # checkout whole history
          fetch-depth: 0

      - name: calculate new version and create changelog content
        id: changelog
        # https://github.com/TriPSs/conventional-changelog-action
        uses: TriPSs/conventional-changelog-action@v5
        with:
          # you can also create separate token to trace action
          github-token: "${{secrets.GITHUB_TOKEN}}"
          # do not create changelog file, the content is used at next step for relase body
          output-file: false
          # do not create additional commit, just tag current commit with the version
          skip-commit: true
          # do not pull - we already checked out the selection we want to use for versioning in previous step
          skip-git-pull: true
          # skip tag push - it will not push but it will tag
          git-push: false

  log_release_tag:
    needs: release_tag
    name: log version output
    runs-on: ubuntu-22.04
    steps:
      - name: info
        run: |
          echo skipped=${{needs.release_tag.outputs.skipped}}
          echo tag=${{needs.release_tag.outputs.tag}}
  docker_image_deeprank2:
    # # it needs to be checked on string value
    # if: needs.release_tag.outputs.skipped == 'false'
    needs: release_tag
    name: docker_image_deeprank2
    uses: ./.github/workflows/_ghcr.yml
    with:
      ghcr_user: ${{github.actor}}
      base_image_name: ghcr.io/deeprank/deeprank2
      image_tag: ${{needs.release_tag.outputs.tag}}
      dockerfile: ./Dockerfile
      docker_context: .
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}
